In [64]:
import numpy as np
from matplotlib import pylab as plt
def f(x):
    return np.sin(x / 5.) * np.exp(x / 10.) + 5. * np.exp(-x / 2.)

In [65]:
x = np.arange(1, 15, 0.1)
y = f(x)
plt.plot(x,y)
plt.show()

In [66]:
A = np.array([])
definition_area = np.array([1, 4, 10, 15])
size = 4
for i in definition_area:
    for j in xrange(0, size):
        A = np.append(A,i**j)
A = A.reshape((size,size))
A

array([[  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00],
       [  1.00000000e+00,   4.00000000e+00,   1.60000000e+01,
          6.40000000e+01],
       [  1.00000000e+00,   1.00000000e+01,   1.00000000e+02,
          1.00000000e+03],
       [  1.00000000e+00,   1.50000000e+01,   2.25000000e+02,
          3.37500000e+03]])

In [67]:
b = f(definition_area)
print b
print f(1)

[ 3.25221687  1.74684595  2.50541641  0.63522142]
3.25221686527


In [68]:
from scipy import linalg
w = linalg.solve(A,b)
print w
print A.dot(w)

[ 4.36264154 -1.29552587  0.19333685 -0.00823565]
[ 3.25221687  1.74684595  2.50541641  0.63522142]


In [37]:
def polynom(x, w, size):
    result = 0.0
    for i in xrange(0, size):
        result += w[i]*(x**i)
    return result

In [69]:
yy = polynom(x, w, size)
plt.plot(x, yy)
plt.show()

In [71]:
file_obj = open('submission-2.txt','w')
string = ''
for i in xrange(0, size):
    string += str(round(w[i],2))
    if i != size-1:
        string += ' '
file_obj.write(string)
file_obj.close()
!cat submission-2.txt

4.36 -1.3 0.19 -0.01